apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-prediction-api
  labels:
    app: iris-prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-prediction-api
  template:
    metadata:
      labels:
        app: iris-prediction-api
    spec:
      containers:
      - name: iris-api-container
        image: # This will be replaced by the CI/CD pipeline
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"