apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-prediction-api
  labels:
    app: iris-prediction-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: iris-prediction-api
  template:
    metadata:
      labels:
        app: iris-prediction-api
    spec:
      containers:
      - name: iris-api-container
        image: # This will be replaced by the CI/CD pipeline
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: GOOGLE_CLOUD_PROJECT
          value: "engaged-mariner-459711-u7"
        # Enhanced health checks for better scaling
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        # Optimized resources for scaling and performance
        resources:
          requests:
            cpu: "200m"      # Reduced to allow more pods per node
            memory: "128Mi"
          limits:
            cpu: "1000m"     # Increased for handling concurrent requests
            memory: "512Mi"  # Increased for better performance under load
        # Graceful shutdown for better rolling updates
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]